<?php

function comment_buddy_comment_update() {
    drupal_set_message("You updated your comment! Just couldn't leave it alone could you...");
}


function comment_buddy_comment_insert() {
    drupal_set_message("You created a comment! You have added your voice to the screaming masses of the internet.");
}


function comment_buddy_comment_delete() {
    drupal_set_message("You removed a comment! WHY?!?!?!?!?");
}
